mongo_type: replica
backup_mode: dedup
replica_name: replica01
server_timeout: 5000
target_host: 192.168.45.126
replicas:
  - mongo_host: 192.168.45.126
    mongo_port: 27017
    mongo_user: admin
    mongo_pass: admin123
    mongo_auth_db: admin
    ssh_user: pendi
    ssh_pass: pendi
  - mongo_host: 192.168.45.127
    mongo_port: 27017
    mongo_user: admin
    mongo_pass: admin123
    mongo_auth_db: admin
    ssh_user: pendi
    ssh_pass: pendi
  - mongo_host: 192.168.45.128
    mongo_port: 27017
    mongo_user: admin
    mongo_pass: admin123
    mongo_auth_db: admin
    ssh_user: pendi
    ssh_pass: pendi