mongo_type: replica
replica_name: myreplica01
server_timeout: 5000
replicas:
  - mongo_host: 192.168.45.141
    mongo_port: 27017
    mongo_user: admin
    mongo_pass: admin123
    mongo_auth_db: admin
    ssh_user: cc
    ssh_pass: cc123
  - mongo_host: 192.168.45.142
    mongo_port: 27017
    mongo_user: admin
    mongo_pass: admin123
    mongo_auth_db: admin
    ssh_user: cc
    ssh_pass: cc123
  - mongo_host: 192.168.45.143
    mongo_port: 27017
    mongo_user: admin
    mongo_pass: admin123
    mongo_auth_db: admin
    ssh_user: cc
    ssh_pass: cc123