mongo_type: shard
backup_mode: dedup
mongos_host: 192.168.45.50
mongos_port: 27017
mongos_user: admin
mongos_pass: 4dm1n123)(*
mongos_auth_db: admin
ssh_user: cc
ssh_pass: cc123
server_timeout: 5000
config_servers:
  replica_name: replconfig01
  target_host: 192.168.45.41
  replicas:
  - mongo_host: 192.168.45.41
    mongo_port: 27019
    mongo_user: admin
    mongo_pass: 4dm1n123)(*
    mongo_auth_db: admin
    ssh_user: cc
    ssh_pass: cc123
  - mongo_host: 192.168.45.42
    mongo_port: 27019
    mongo_user: admin
    mongo_pass: 4dm1n123)(*
    mongo_auth_db: admin
    ssh_user: cc
    ssh_pass: cc123
  - mongo_host: 192.168.45.43
    mongo_port: 27019
    mongo_user: admin
    mongo_pass: 4dm1n123)(*
    mongo_auth_db: admin
    ssh_user: cc
    ssh_pass: cc123
shards:
  - replica_name: shardreplica01
    target_host: 192.168.45.44
    replicas:
    - mongo_host: 192.168.45.44
      mongo_port: 27018
      mongo_user: admin
      mongo_pass: 4dm1n123)(*
      mongo_auth_db: admin
      ssh_user: cc
      ssh_pass: cc123
    - mongo_host: 192.168.45.45
      mongo_port: 27018
      mongo_user: admin
      mongo_pass: 4dm1n123)(*
      mongo_auth_db: admin
      ssh_user: cc
      ssh_pass: cc123
    - mongo_host: 192.168.45.46
      mongo_port: 27018
      mongo_user: admin
      mongo_pass: 4dm1n123)(*
      mongo_auth_db: admin
      ssh_user: cc
      ssh_pass: cc123
  - replica_name: shardreplica02
    target_host: 192.168.45.47
    replicas:
    - mongo_host: 192.168.45.47
      mongo_port: 27018
      mongo_user: admin
      mongo_pass: 4dm1n123)(*
      mongo_auth_db: admin
      ssh_user: cc
      ssh_pass: cc123
    - mongo_host: 192.168.45.48
      mongo_port: 27018
      mongo_user: admin
      mongo_pass: 4dm1n123)(*
      mongo_auth_db: admin
      ssh_user: cc
      ssh_pass: cc123
    - mongo_host: 192.168.45.49
      mongo_port: 27018
      mongo_user: admin
      mongo_pass: 4dm1n123)(*
      mongo_auth_db: admin
      ssh_user: cc
      ssh_pass: cc123