mongo_type: replica
replica_name: bukalapak-cluster-1
mongo_version: 3.2
server_timeout: 10000
target_host: 127.0.0.1
lvm_volume: /dev/raid6/mongodb
s3_bucket_name: backup-mongo
replicas:
  - mongo_host: 127.0.0.1
    mongo_port: 27017
    mongo_user: secret
    mongo_pass: secret
    mongo_auth_db: admin
    mongo_db_path: /data/mongodb
    ssh_user: secret
    ssh_pass: secret
