mongo_type: replica
replica_name: replica01
mongo_version: 3.2
server_timeout: 10000
target_host: 192.168.45.126
lvm_volume: /dev/monggo-1-vg/mongodb
replicas:
  - mongo_host: 192.168.45.126
    mongo_port: 27017
    mongo_user: admin
    mongo_pass: admin123
    mongo_auth_db: admin
    mongo_db_path: /data/mongodb
    ssh_user: root
    ssh_pass: pendi
  - mongo_host: 192.168.45.127
    mongo_port: 27017
    mongo_user: admin
    mongo_pass: admin123
    mongo_auth_db: admin
    mongo_db_path: /data/mongodb
    ssh_user: root
    ssh_pass: pendi
  - mongo_host: 192.168.45.128
    mongo_port: 27017
    mongo_user: admin
    mongo_pass: admin123
    mongo_auth_db: admin
    mongo_db_path: /data/mongodb
    ssh_user: root
    ssh_pass: pendi